version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      - MONGO_URI=${MONGO_URI}

volumes:
  db: