version: '3.8'

services:
  app:
    image: node:latest
    container_name: express-jwt-auth
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      - MONGO_URI=${MONGO_URI}

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: